"""
Trade intent REST endpoints.

POST   /trade-intents              — submit a new TradeIntent (hotkey → backend)
POST   /trade-intents/{id}/confirm — confirm an amber (AWAITING_CONFIRMATION) intent
DELETE /trade-intents/{id}         — cancel a pending-confirmation intent
GET    /trade-intents/{id}         — status of an intent (for UI polling / audit)

The coordinator is accessed via app.state.execution_coordinator.
If no coordinator is wired (API running standalone), all routes return 503.

Idempotency-Key header:
  Must be provided on POST /trade-intents. Generated by the frontend from the
  specific input event (e.g. "browser-session-abc:keydown-event-42"). Retrying
  the same HTTP request with the same key returns the original response.
"""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import uuid4

from fastapi import APIRouter, Header, HTTPException, Request
from pydantic import BaseModel

from alpha.engines.execution.models import (
    ExecutionPolicy,
    ProtectionPolicy,
    QuoteSnapshot,
    TradeIntent,
)
from alpha.models.enums import IntentSource, PriceMode, TradeAction

router = APIRouter(prefix="/trade-intents", tags=["execution"])

_UTC = timezone.utc


# ── Request / Response models ─────────────────────────────────────────────────

class QuoteSnapshotInput(BaseModel):
    bid: Decimal
    ask: Decimal
    last: Decimal
    timestamp: datetime


class TradeIntentRequest(BaseModel):
    """
    Payload from the web frontend.

    instrument_id: symbol as known to the runtime (e.g. "MNQ-09")
    action: one of open_long, open_short, flatten
    quantity: number of contracts (V1: must be 1)
    price_mode: execution policy (V1: marketable_limit only)
    stop_distance_ticks: how many ticks below/above entry to place stop
    target_distance_ticks: None = no take-profit order
    client_quote: snapshot of what the browser saw at keypress (contextual only)
    """
    instrument_id: str
    action: TradeAction
    quantity: Decimal = Decimal("1")
    price_mode: PriceMode = PriceMode.MARKETABLE_LIMIT
    stop_distance_ticks: int = 8
    target_distance_ticks: int | None = 16
    client_quote: QuoteSnapshotInput | None = None


# ── Helpers ───────────────────────────────────────────────────────────────────

def _get_coordinator(request: Request) -> Any:
    coordinator = getattr(request.app.state, "execution_coordinator", None)
    if coordinator is None:
        raise HTTPException(
            status_code=503,
            detail="Execution subsystem not available — runtime not running",
        )
    return coordinator


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("", status_code=202)
async def submit_trade_intent(
    body: TradeIntentRequest,
    request: Request,
    idempotency_key: str = Header(default=""),
) -> dict:
    """
    Submit a new TradeIntent.

    Returns 202 Accepted immediately. Check `status` in the response:
      - approved / active  → order submitted to broker
      - awaiting_confirmation → amber: call POST /confirm within 10s
      - rejected           → hard risk blocked it (see explanation)
    """
    coordinator = _get_coordinator(request)

    # Generate idempotency key if frontend didn't provide one
    if not idempotency_key:
        idempotency_key = f"server-generated:{uuid4().hex}"

    client_quote = None
    if body.client_quote:
        client_quote = QuoteSnapshot(
            instrument_id=body.instrument_id,
            bid=body.client_quote.bid,
            ask=body.client_quote.ask,
            last=body.client_quote.last,
            timestamp=body.client_quote.timestamp,
        )

    intent = TradeIntent(
        idempotency_key=idempotency_key,
        created_at=datetime.now(_UTC),
        instrument_id=body.instrument_id,
        action=body.action,
        quantity=body.quantity,
        execution_policy=ExecutionPolicy(price_mode=body.price_mode),
        protection_policy=ProtectionPolicy(
            stop_distance_ticks=body.stop_distance_ticks,
            target_distance_ticks=body.target_distance_ticks,
            use_broker_bracket=True,
        ),
        source=IntentSource.HOTKEY,
        client_quote=client_quote,
    )

    response = await coordinator.submit_intent(intent)
    return response.model_dump()


@router.post("/{intent_id}/confirm", status_code=200)
async def confirm_trade_intent(intent_id: str, request: Request) -> dict:
    """
    Confirm an amber intent (AWAITING_CONFIRMATION).

    Must be called within 10 seconds of the original submission.
    Revalidates market state, kill switch, and exposure before submitting.
    """
    coordinator = _get_coordinator(request)
    response = await coordinator.confirm_intent(intent_id)
    return response.model_dump()


@router.delete("/{intent_id}", status_code=200)
async def cancel_trade_intent(intent_id: str, request: Request) -> dict:
    """Cancel a pending-confirmation intent (user pressed Esc)."""
    coordinator = _get_coordinator(request)
    response = await coordinator.cancel_intent(intent_id)
    return response.model_dump()


@router.get("/{intent_id}", status_code=200)
async def get_trade_intent(intent_id: str, request: Request) -> dict:
    """Current status of an intent. Used by UI for polling after submission."""
    coordinator = _get_coordinator(request)
    history = await coordinator._journal.get_intent_history(intent_id)
    status = coordinator._intent_status.get(intent_id)
    if status is None:
        raise HTTPException(status_code=404, detail=f"Intent {intent_id!r} not found")
    return {
        "intent_id": intent_id,
        "status": status,
        "events": [
            {
                "event": e.event,
                "timestamp": e.timestamp.isoformat(),
                "detail": e.detail,
            }
            for e in history
        ],
    }
